
version: '3'
services:
  mysql:
    image: mysql:8.2
    restart: unless-stopped
    tty: true
    ports:
      - ${DBPORT}:3306
    environment:
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_DB=${DBNAME}
      - MYSQL_HOST=${DBHOST}