
version: '3'
services:
  mysql:
    image: mysql:8.2
    restart: unless-stopped
    tty: true
    ports:
      - ${DBPORT}:3306
    environment:
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DBHOST}
      - MYSQL_ROOT_PASSWORD=${DBPASS_ROOT}



